### ISSUE TITLE
It would be great that we can add English name in the maintainer/committer list

### ISSUE THREAD

**Issue by shenli** [pingcap/community#523]
For maintainer: https://github.com/pingcap/community/blob/master/architecture/maintainer-list.md
For the committer, it will link to a page on tidb.io with Chinese content only. https://tidb.io/archived/events//organization/

**Comment by tisonkun** [comment]
Thanks for reporting this issue @shenli !

The content under this folder ("architecture") is actually outdated.

* pmc-list: we have no longer PMC.
* committer-list: it is reflected by content under "special-interest-group" and being moved in #522 with the proposal #516 .
* maintainer-list: it doesn't fit governance model now and in the ongoing proposal #516 any more. However, I highly appreciate those maintainers work ever.

Thus, I tend to create a pull request to:

* Remove pmc-list.md, since it is invalid.
* Remove committer-list,md, since it is moved to sig folder.
* Update maintainer-list.md with English name, and later move it to archive folder but respect you guys' contributions.

**Comment by tisonkun** [comment]
... well I think we can just do the archive in place at once. As part of #525 .
